version: "3.5"
services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:8080
